require_relative 'config/environment.rb'

desc "puts Hello world"
task :hello do
  puts "Hello World"
end

desc "open a console session"
task :console do
  Pry.start
end

desc "testing"
task :tweeter do
  TweetsApp.new.call
end
